enum GestureEffects {
    static let all: [Effect] = [
        Effect.gesturesRubberBand,
        Effect.gesturesFling,
        Effect.gesturesPiPSnap,
        Effect.gesturesJelly,
        Effect.gesturesPinchRotate,
        Effect.gesturesSwipeActions,
        Effect.gesturesDragReorder,
        Effect.gesturesSpringChain,
        Effect.gesturesChargeBurst,
        Effect.gesturesDragDismiss,
        Effect.gesturesSlideToConfirm,
        Effect.gesturesMagnifierLoupe,
        Effect.gesturesGooeyBlobs,
        Effect.gesturesVerletRope,
        Effect.gesturesNewtonsCradle,
        Effect.gesturesPhotoViewer,
        // Drag & spring variations
        Effect.gesturesMagneticSnap,
        Effect.gesturesElasticTether,
        Effect.gesturesPendulumSwing,
        // Throw & snap variations
        Effect.gesturesGravityToss,
        Effect.gesturesDetentSheet,
        // Physics toys
        Effect.gesturesCoilSpring,
        Effect.gesturesOrbitSlingshot,
        // List gestures
        Effect.gesturesSwipeComplete,
        Effect.gesturesStagedSwipe,
        Effect.gesturesDragSelect,
        // Pinch & zoom
        Effect.gesturesPinchGrid,
        Effect.gesturesPinchOpen,
        // Slide to confirm
        Effect.gesturesStretchSlide,
        Effect.gesturesNotchSlide,
        Effect.gesturesArcSlide,
        Effect.gesturesPullCord,
        // Round 2
        Effect.gesturesJoystick,
        Effect.gesturesStickyGoo,
        Effect.gesturesPaperToss,
        Effect.gesturesSpinWheel,
        Effect.gesturesZoomTimeline,
        Effect.gesturesPullToCreate,
        Effect.gesturesKanbanDrag,
        Effect.gesturesBallPit,
        Effect.gesturesSoftBody,
        Effect.gesturesClothGrid,
        Effect.gesturesSwipeUpUnlock,
        // Round 2, part B
        Effect.gesturesMeshWarp,
        Effect.gesturesBalloonTether,
        Effect.gesturesSlinky,
        Effect.gesturesCurlingTarget,
        Effect.gesturesAirHockey,
        Effect.gesturesRotateKnob,
        Effect.gesturesSqueezeCrumple,
        Effect.gesturesSwipeReply,
        Effect.gesturesJiggleGrid,
        Effect.gesturesDoublePendulum,
        Effect.gesturesSandFall,
        Effect.gesturesBubbleWrap,
        Effect.gesturesWaveString,
        Effect.gesturesAnswerCall,
    ]
}
