enum FeedbackEffects {
    static let all: [Effect] = [
        Effect.feedbackToast,
        Effect.feedbackSuccessCheck,
        Effect.feedbackErrorShake,
        Effect.feedbackInlineValidation,
        Effect.feedbackConfetti,
        Effect.feedbackIsland,
        Effect.feedbackConnectionBanner,
        Effect.feedbackBadgeBounce,
        Effect.feedbackUndoSnackbar,
        Effect.feedbackAlertPop,
        Effect.feedbackStackedBanners,
        Effect.feedbackSpotlight,
        Effect.feedbackCopy,
        Effect.feedbackReactionPicker,
        Effect.feedbackPullRefresh,
        // Toast variations
        Effect.feedbackHingeToast,
        Effect.feedbackMorphToast,
        // Success variations
        Effect.feedbackSparkBurst,
        Effect.feedbackLevelUp,
        // Error variations
        Effect.feedbackGlitchError,
        Effect.feedbackLimitBounce,
        Effect.feedbackFaceIDFail,
        // Badge variations
        Effect.feedbackStreakFlame,
        Effect.feedbackPresencePing,
        Effect.feedbackFloatingHearts,
        // Overlay variations
        Effect.feedbackRecedingSheet,
        Effect.feedbackTipPopover,
        Effect.feedbackDropAlert,
        // Refresh variations
        Effect.feedbackGooRefresh,
        Effect.feedbackSunRefresh,
        Effect.feedbackLetterRefresh,
        Effect.feedbackDotsRefresh,
        // Round 2
        Effect.feedbackProgressToast,
        Effect.feedbackAchievementBanner,
        Effect.feedbackPaymentDone,
        Effect.feedbackFireworks,
        Effect.feedbackCoinReward,
        Effect.feedbackCardDeclined,
        Effect.feedbackCounterBadge,
        Effect.feedbackTypingBubble,
        Effect.feedbackSilentHUD,
        Effect.feedbackAutosavePulse,
        Effect.feedbackThreadRefresh,
        // Round 2, part B
        Effect.feedbackSwipeToast,
        Effect.feedbackExpandToast,
        Effect.feedbackNotchDrop,
        Effect.feedbackOrderBox,
        Effect.feedbackAllDoneList,
        Effect.feedbackStickerSlap,
        Effect.feedbackRetryCountdown,
        Effect.feedbackEmptyState,
        Effect.feedbackNewMessagesPill,
        Effect.feedbackLiveBadge,
        Effect.feedbackScreenshotThumb,
        Effect.feedbackPermissionDialog,
        Effect.feedbackActionSheet,
        Effect.feedbackRocketRefresh,
    ]
}
