import type { DemoMap } from "../../kit/types";

/** Charts · 数据与图表: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "charts.bar-grow": () => import("./bar-grow"),
  "charts.line-draw": () => import("./line-draw"),
  "charts.donut-explode": () => import("./donut-explode"),
  "charts.gauge-needle": () => import("./gauge-needle"),
  "charts.activity-rings": () => import("./activity-rings"),
  "charts.scrub-tooltip": () => import("./scrub-tooltip"),
  "charts.heatmap-cascade": () => import("./heatmap-cascade"),
  "charts.kpi-count-up": () => import("./kpi-count-up"),
  "charts.sparkline-stream": () => import("./sparkline-stream"),
  "charts.bar-race": () => import("./bar-race"),
  "charts.radar-morph": () => import("./radar-morph"),
  "charts.range-morph": () => import("./range-morph"),
  "charts.candlestick-live": () => import("./candlestick-live"),
  "charts.donut-to-bars": () => import("./donut-to-bars"),
  "charts.stacked-bars": () => import("./stacked-bars"),
  "charts.liquid-bars": () => import("./liquid-bars"),
  "charts.brick-bars": () => import("./brick-bars"),
  "charts.segmented-gauge": () => import("./segmented-gauge"),
  "charts.rose-bloom": () => import("./rose-bloom"),
  "charts.bars-to-line": () => import("./bars-to-line"),
  "charts.scatter-histogram": () => import("./scatter-histogram"),
  "charts.grouped-stacked": () => import("./grouped-stacked"),
  "charts.odometer-kpi": () => import("./odometer-kpi"),
  "charts.bullet-kpi": () => import("./bullet-kpi"),
  "charts.waffle-kpi": () => import("./waffle-kpi"),
  // Round 2
  "charts.waterfall": () => import("./waterfall"),
  "charts.lollipop": () => import("./lollipop"),
  "charts.range-brush": () => import("./range-brush"),
  "charts.stacked-area": () => import("./stacked-area"),
  "charts.ecg-live": () => import("./ecg-live"),
  "charts.line-compare": () => import("./line-compare"),
  "charts.radial-bars": () => import("./radial-bars"),
  "charts.sunburst": () => import("./sunburst"),
  "charts.funnel-flow": () => import("./funnel-flow"),
  "charts.trend-pill": () => import("./trend-pill"),
  "charts.treemap": () => import("./treemap"),
  "charts.diverging": () => import("./diverging"),
  "charts.pyramid": () => import("./pyramid"),
  "charts.bar-drilldown": () => import("./bar-drilldown"),
  "charts.forecast-band": () => import("./forecast-band"),
  "charts.threshold-split": () => import("./threshold-split"),
  "charts.legend-focus": () => import("./legend-focus"),
  "charts.pan-zoom": () => import("./pan-zoom"),
  "charts.radial-schedule": () => import("./radial-schedule"),
  "charts.hemicycle": () => import("./hemicycle"),
  "charts.thermometer": () => import("./thermometer"),
  "charts.leaderboard": () => import("./leaderboard"),
  "charts.scatter-cluster": () => import("./scatter-cluster"),
  "charts.dot-matrix-morph": () => import("./dot-matrix-morph"),
  "charts.sankey-flow": () => import("./sankey-flow"),
};
