enum LoadingEffects {
    static let all: [Effect] = [
        Effect.loadingLoadButton,
        Effect.loadingDownloadButton,
        Effect.loadingArcSpinner,
        Effect.loadingDotBounce,
        Effect.loadingSkeleton,
        Effect.loadingBlurUp,
        Effect.loadingAIGenerating,
        Effect.loadingGlowBar,
        Effect.loadingProgressRing,
        Effect.loadingStoryBars,
        Effect.loadingLiquidFill,
        Effect.loadingOrbitDots,
        Effect.loadingAudioWave,
        Effect.loadingPulseRings,
        Effect.loadingSquareGrid,
        Effect.loadingIndeterminateBar,
        Effect.loadingActivityPetals,
        // Spinner variations
        Effect.loadingGooeyOrbit,
        Effect.loadingGyroscope,
        Effect.loadingFlipTile,
        Effect.loadingInfinityComet,
        // Dots & pulses
        Effect.loadingHeartbeat,
        // Progress bar variations
        Effect.loadingSegmentBar,
        Effect.loadingLiquidBar,
        Effect.loadingTooltipBar,
        Effect.loadingCandyStripes,
        // Progress ring variations
        Effect.loadingTickRing,
        Effect.loadingInstallPie,
        Effect.loadingElasticRing,
        Effect.loadingRingToCheck,
        Effect.loadingDashFlowRing,
        // Loading button variations
        Effect.loadingFillButton,
        Effect.loadingDotsButton,
        Effect.loadingTraceButton,
        // Placeholder variations
        Effect.loadingBreathingSkeleton,
        Effect.loadingMosaicResolve,
        // Round 2
        Effect.loadingDNAHelix,
        Effect.loadingShapeShifter,
        Effect.loadingFoldingCube,
        Effect.loadingHourglass,
        Effect.loadingVoiceOrb,
        Effect.loadingStreamIn,
        Effect.loadingScanReveal,
        Effect.loadingStageLoader,
        Effect.loadingPercentPill,
        Effect.loadingCountdownRing,
        Effect.loadingLaunchButton,
        // Round 2, part B
        Effect.loadingPendulumWave,
        Effect.loadingAtomOrbit,
        Effect.loadingSquashBall,
        Effect.loadingSnakePixels,
        Effect.loadingRippleDrop,
        Effect.loadingSkeletonResolve,
        Effect.loadingMapTiles,
        Effect.loadingMilestones,
        Effect.loadingBufferScrub,
        Effect.loadingFileQueue,
        Effect.loadingOrbitRing,
        Effect.loadingHalfGauge,
        Effect.loadingPayButton,
        Effect.loadingSyncButton,
    ]
}
