enum LoadingEffects {
    static let all: [Effect] = [
        .loadingLoadButton,
        .loadingDownloadButton,
        .loadingArcSpinner,
        .loadingDotBounce,
        .loadingSkeleton,
        .loadingBlurUp,
        .loadingAIGenerating,
        .loadingGlowBar,
        .loadingProgressRing,
        .loadingStoryBars,
        .loadingLiquidFill,
        .loadingOrbitDots,
        .loadingAudioWave,
        .loadingPulseRings,
        .loadingSquareGrid,
        .loadingIndeterminateBar,
        .loadingActivityPetals,
        // Spinner variations
        .loadingGooeyOrbit,
        .loadingGyroscope,
        .loadingFlipTile,
        .loadingInfinityComet,
        // Dots & pulses
        .loadingHeartbeat,
        // Progress bar variations
        .loadingSegmentBar,
        .loadingLiquidBar,
        .loadingTooltipBar,
        .loadingCandyStripes,
        // Progress ring variations
        .loadingTickRing,
        .loadingInstallPie,
        .loadingElasticRing,
        .loadingRingToCheck,
        .loadingDashFlowRing,
        // Loading button variations
        .loadingFillButton,
        .loadingDotsButton,
        .loadingTraceButton,
        // Placeholder variations
        .loadingBreathingSkeleton,
        .loadingMosaicResolve,
        // Round 2
        .loadingDNAHelix,
        .loadingShapeShifter,
        .loadingFoldingCube,
        .loadingHourglass,
        .loadingVoiceOrb,
        .loadingStreamIn,
        .loadingScanReveal,
        .loadingStageLoader,
        .loadingPercentPill,
        .loadingCountdownRing,
        .loadingLaunchButton,
        // Round 2, part B
        .loadingPendulumWave,
        .loadingAtomOrbit,
        .loadingSquashBall,
        .loadingSnakePixels,
        .loadingRippleDrop,
        .loadingSkeletonResolve,
        .loadingMapTiles,
        .loadingMilestones,
        .loadingBufferScrub,
        .loadingFileQueue,
        .loadingOrbitRing,
        .loadingHalfGauge,
        .loadingPayButton,
        .loadingSyncButton,
    ]
}
